cors.allowed-origins=*

# To enable OAuth 2.0 Protected Resource Metadata (RFC9728) in sync with the MCP authorization specification
# (https://modelcontextprotocol.io/specification/2025-06-18/basic/authorization#overview), configure the properties below.
# mcp.oauth2.metadata.authorization-servers=
# mcp.oauth2.metadata.scopes-supported=

# Overrides the prefix for MCP tools.
# The `<database_name>` wildcard is optional and is automatically replaced by the name of the connected database.
# mcp.tools.prefix=denodo_<database_name>_

# Sets a character limit for the names of all generated tools
# mcp.tools.name-length-limit=64

# This tag creates individual tools to query views that have been tagged with it.
mcp.tools.view-tag=mcp

# Default max row limit for dedicated view tools (mcp.tools.view-tag).
# Overridden if the user explicitly requests a different limit or requests ALL results.
# Set to -1 or leave empty to disable the default limit
# mcp.tools.view.default-row-limit=100

mcp.transport.sse.endpoint=/sse
mcp.transport.streamable-http.endpoint=/mcp

# By default, the resources URI host is the same as the one specified in the vdp.datasource.jdbc-url property.
# You can override it by setting the following property:
# mcp.resources.host=

# Enables or disables periodic schema refresh to notify clients of tool and resource changes.
mcp.schema-refresh.enabled=true

# By default, inactive sessions are cleaned up every hour.
# The formats accepted are for this interval based on the ISO-8601 duration format PnDTnHnMn.nS.
# (https://en.wikipedia.org/wiki/ISO_8601#:~:text=Durations%20define%20the%20amount%20of,that%20follow%20the%20%5Bn%5D.)
spring.ai.mcp.server.keep-alive-interval=PT1H

vdp.datasource.driver-class-name=com.denodo.vdp.jdbc.Driver
vdp.datasource.jdbc-url=jdbc:vdb://localhost:49999/?noAuth=true
